# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_app', '0002_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='wishers',
            field=models.ManyToManyField(related_name='items', to='wish_list_app.User'),
        ),
    ]
